name: dart_rl
description: A simple Dart package implementing reinforcement learning algorithms (Q-Learning, SARSA, Expected-SARSA).
version: 0.2.0-alpha.2
homepage: https://github.com/kekko7072/dart_rl

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  test: ^1.21.0
