name: dart_rl
description: A Dart package implementing reinforcement learning algorithms (SARSA, Q-Learning, Expected-SARSA) for both Dart and Flutter applications.
version: 0.1.0-alpha.1
homepage: https://github.com/kekko7072/dart_rl

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.21.0
  pedantic: ^1.11.0
